### ISSUE TITLE
it's now banned on heroku

### ISSUE THREAD

**Issue by thinkbyit** [MysteryDemon/TGVid-Comp#3]
make it deployable on heroku 😥

**Comment by AshutoshGoswami24** [comment]
ah not rapo bro

**Comment by AshutoshGoswami24** [comment]
use koyeb render or many more

**Comment by thinkbyit** [comment]
in koyeb it's not deploying , and in render i deployed , but it gives very slow speed

**Comment by AshutoshGoswami24** [comment]
ITS BECOSE FFMPEG WANTS 2v CPU ok

Use https://www.heroku.com/ && https://railway.app/
